#!/bin/sh

clear
COMPILE_FLAGS="-g -Wall -Wextra -Os"
g++ $COMPILE_FLAGS a.out\
    -I src -I src/vendor/glm -I src/vendor/glm/gtc -I src/objects\
    src/*.cc src/objects/*.cc -lglfw -lGLEW -lGLU -lGL\
    && gdb a.out
